### ISSUE TITLE
Couldn't compile

### ISSUE THREAD

**Issue by navta** [opendcd/opendcd#1]
I'm following the "Quick Installation Guide", but it gives the following error:

`> cd src/bin`
`> make`
`make: *** No rule to make target ../include/dcd/arc-decoder.h, needed by dcd-recog.cc.  Stop.`

**Comment by howardhamilton** [comment]
I'm having exactly the same issue as well, and I can't find any reference to arc-decoder.h in the repo.

**Comment by danielrenshaw** [comment]
I've created a PR that seems to enable OpenDCD to build successfully: https://github.com/opendcd/opendcd/pull/4

**Comment by danielrenshaw** [comment]
PR #4 has now been merged. It should now be easier to compile.

**Comment by navta** [comment]
I still got an error. But this time as follow:

3rdparty/local/lib/fst/libfstfarscript.so: undefined reference to `fst::IsSTTable(std::string const&)'

Does it has to do with the OpenFst version? The script install version 1.4.1

**Comment by danielrenshaw** [comment]
I can confirm this happens when building on a clean PC (an AWS EC2 linux instance). I'm not sure what the cause is. I tried compiling with the latest version of OpenFST (1.5.1) and an older version (1.3.4) but different errors arose in both cases.

I don't know why it worked on my desktop PC but it may be due to a compiler version difference. I've been unable to identify an exact cause let alone a solution.

**Comment by tao-githup** [comment]
> I still got an error. But this time as follow:
> 
> 3rdparty/local/lib/fst/libfstfarscript.so: undefined reference to `fst::IsSTTable(std::string const&)'
> 
> Does it has to do with the OpenFst version? The script install version 1.4.1

Hello, have you solved the problem?

**Comment by navta** [comment]
Solved by adding -lfstfar to src/bin/Makefile at the end of dcd-recog
